// Company job boards Job Finder and the resume builder's job search read. Every entry was checked
// against its ATS's public API on 2026-10-10 and had open jobs. Format: [board id, company, website].

export const GREENHOUSE = [
  ['affirm', 'Affirm', 'affirm.com'],
  ['agoda', 'Agoda', 'agoda.com'],
  ['airbnb', 'Airbnb', 'airbnb.com'],
  ['airtable', 'Airtable', 'airtable.com'],
  ['anthropic', 'Anthropic', 'anthropic.com'],
  ['asana', 'Asana', 'asana.com'],
  ['attentive', 'Attentive', 'attentive.com'],
  ['braze', 'Braze', 'braze.com'],
  ['brex', 'Brex', 'brex.com'],
  ['calm', 'Calm', 'calm.com'],
  ['careem', 'Careem', 'careem.com'],
  ['carta', 'Carta', 'carta.com'],
  ['celonis', 'Celonis', 'celonis.com'],
  ['chime', 'Chime', 'chime.com'],
  ['clear', 'CLEAR', 'clearme.com'],
  ['cloudflare', 'Cloudflare', 'cloudflare.com'],
  ['coinbase', 'Coinbase', 'coinbase.com'],
  ['contentful', 'Contentful', 'contentful.com'],
  ['coursera', 'Coursera', 'coursera.org'],
  ['databricks', 'Databricks', 'databricks.com'],
  ['datadog', 'Datadog', 'datadoghq.com'],
  ['discord', 'Discord', 'discord.com'],
  ['dropbox', 'Dropbox', 'dropbox.com'],
  ['druva', 'Druva', 'druva.com'],
  ['duolingo', 'Duolingo', 'duolingo.com'],
  ['elastic', 'Elastic', 'elastic.co'],
  ['epicgames', 'Epic Games', 'epicgames.com'],
  ['figma', 'Figma', 'figma.com'],
  ['flexport', 'Flexport', 'flexport.com'],
  ['gitlab', 'GitLab', 'gitlab.com'],
  ['glance', 'Glance', 'glance.com'],
  ['gleanwork', 'Glean', 'glean.com'],
  ['glossier', 'Glossier', 'glossier.com'],
  ['gocardless', 'GoCardless', 'gocardless.com'],
  ['groww', 'Groww', 'groww.in'],
  ['gusto', 'Gusto', 'gusto.com'],
  ['gymshark', 'Gymshark', 'gymshark.com'],
  ['highradius', 'HighRadius', 'highradius.com'],
  ['inmobi', 'InMobi', 'inmobi.com'],
  ['instacart', 'Instacart', 'instacart.com'],
  ['intercom', 'Intercom', 'intercom.com'],
  ['khanacademy', 'Khan Academy', 'khanacademy.org'],
  ['lattice', 'Lattice', 'lattice.com'],
  ['lyft', 'Lyft', 'lyft.com'],
  ['medium', 'Medium', 'medium.com'],
  ['mercury', 'Mercury', 'mercury.com'],
  ['mixpanel', 'Mixpanel', 'mixpanel.com'],
  ['mongodb', 'MongoDB', 'mongodb.com'],
  ['monzo', 'Monzo', 'monzo.com'],
  ['n26', 'N26', 'n26.com'],
  ['netlify', 'Netlify', 'netlify.com'],
  ['observeai', 'Observe.AI', 'observe.ai'],
  ['okta', 'Okta', 'okta.com'],
  ['oscar', 'Oscar Health', 'hioscar.com'],
  ['peloton', 'Peloton', 'onepeloton.com'],
  ['pinterest', 'Pinterest', 'pinterest.com'],
  ['reddit', 'Reddit', 'reddit.com'],
  ['riotgames', 'Riot Games', 'riotgames.com'],
  ['robinhood', 'Robinhood', 'robinhood.com'],
  ['roblox', 'Roblox', 'roblox.com'],
  ['rubrik', 'Rubrik', 'rubrik.com'],
  ['samsara', 'Samsara', 'samsara.com'],
  ['scaleai', 'Scale AI', 'scale.com'],
  ['similarweb', 'Similarweb', 'similarweb.com'],
  ['slice', 'Slice', 'slicelife.com'],
  ['squarespace', 'Squarespace', 'squarespace.com'],
  ['stripe', 'Stripe', 'stripe.com'],
  ['taboola', 'Taboola', 'taboola.com'],
  ['toast', 'Toast', 'toasttab.com'],
  ['turing', 'Turing', 'turing.com'],
  ['twilio', 'Twilio', 'twilio.com'],
  ['twitch', 'Twitch', 'twitch.tv'],
  ['udemy', 'Udemy', 'udemy.com'],
  ['vercel', 'Vercel', 'vercel.com'],
  ['voxmedia', 'Vox Media', 'voxmedia.com'],
  ['wise', 'Wise', 'wise.com'],
  ['zocdoc', 'Zocdoc', 'zocdoc.com'],
];

export const LEVER = [
  ['cred', 'CRED', 'cred.club'],
  ['fampay', 'FamPay', 'famapp.in'],
  ['epifi', 'Fi Money', 'fi.money'],
  ['hevodata', 'Hevo Data', 'hevodata.com'],
  ['matchgroup', 'Match Group', 'mtch.com'],
  ['meesho', 'Meesho', 'meesho.com'],
  ['mindtickle', 'Mindtickle', 'mindtickle.com'],
  ['palantir', 'Palantir', 'palantir.com'],
  ['paytm', 'Paytm', 'paytm.com'],
  ['pocketfm', 'Pocket FM', 'pocketfm.com'],
  ['ro', 'Ro', 'ro.co'],
  ['spotify', 'Spotify', 'spotify.com'],
  ['theathletic', 'The Athletic', 'theathletic.com'],
  ['toptal', 'Toptal', 'toptal.com'],
  ['zeta', 'Zeta', 'zeta.tech'],
  ['zoox', 'Zoox', 'zoox.com'],
];

export const ASHBY = [
  ['1password', '1Password', '1password.com'],
  ['airwallex', 'Airwallex', 'airwallex.com'],
  ['amplitude', 'Amplitude', 'amplitude.com'],
  ['atlan', 'Atlan', 'atlan.com'],
  ['benchling', 'Benchling', 'benchling.com'],
  ['clerk', 'Clerk', 'clerk.com'],
  ['cohere', 'Cohere', 'cohere.com'],
  ['confluent', 'Confluent', 'confluent.io'],
  ['docker', 'Docker', 'docker.com'],
  ['elevenlabs', 'ElevenLabs', 'elevenlabs.io'],
  ['harvey', 'Harvey', 'harvey.ai'],
  ['hightouch', 'Hightouch', 'hightouch.com'],
  ['linear', 'Linear', 'linear.app'],
  ['miro', 'Miro', 'miro.com'],
  ['notion', 'Notion', 'notion.so'],
  ['nubank', 'Nubank', 'nubank.com.br'],
  ['openai', 'OpenAI', 'openai.com'],
  ['oyster', 'Oyster', 'oysterhr.com'],
  ['perplexity', 'Perplexity', 'perplexity.ai'],
  ['pinecone', 'Pinecone', 'pinecone.io'],
  ['plaid', 'Plaid', 'plaid.com'],
  ['posthog', 'PostHog', 'posthog.com'],
  ['quora', 'Quora', 'quora.com'],
  ['ramp', 'Ramp', 'ramp.com'],
  ['replit', 'Replit', 'replit.com'],
  ['runway', 'Runway', 'runwayml.com'],
  ['sarvam', 'Sarvam AI', 'sarvam.ai'],
  ['sentry', 'Sentry', 'sentry.io'],
  ['snowflake', 'Snowflake', 'snowflake.com'],
  ['spotdraft', 'SpotDraft', 'spotdraft.com'],
  ['substack', 'Substack', 'substack.com'],
  ['supabase', 'Supabase', 'supabase.com'],
  ['wealthsimple', 'Wealthsimple', 'wealthsimple.com'],
  ['webflow', 'Webflow', 'webflow.com'],
  ['writer', 'Writer', 'writer.com'],
  ['zapier', 'Zapier', 'zapier.com'],
];

export const SMARTRECRUITERS = [
  ['AccorHotel', 'Accor', 'accor.com'],
  ['AveryDennison', 'Avery Dennison', 'averydennison.com'],
  ['BoschGroup', 'Bosch', 'bosch.com'],
  ['Cars24', 'Cars24', 'cars24.com'],
  ['Colliers', 'Colliers', 'colliers.com'],
  ['Deloitte6', 'Deloitte', 'deloitte.com'],
  ['Experian', 'Experian', 'experian.com'],
  ['Freshworks', 'Freshworks', 'freshworks.com'],
  ['McDonaldsCorporation', "McDonald's", 'mcdonalds.com'],
  ['NielsenIQ', 'Nielsen', 'nielsen.com'],
  ['Securitas', 'Securitas', 'securitas.com'],
  ['ServiceNow', 'ServiceNow', 'servicenow.com'],
  ['Sodexo', 'Sodexo', 'sodexo.com'],
  ['Swiggy', 'Swiggy', 'swiggy.com'],
  ['Ubisoft2', 'Ubisoft', 'ubisoft.com'],
  ['WesternDigital', 'Western Digital', 'westerndigital.com'],
];

export const WORKABLE = [
  ['blueground', 'Blueground', 'theblueground.com'],
  ['seekho', 'Seekho', 'seekho.ai'],
  ['skroutz', 'Skroutz', 'skroutz.gr'],
  ['yapily', 'Yapily', 'yapily.com'],
];
