import type { CodingProblem } from './codingProblems';

// Four learning levels layered on top of the Easy / Medium / Hard difficulty.
// codingProblems.ts is generated by backend/scripts/build-problems.mjs, so levels live here instead.
export const LEVELS = ['Beginner', 'Intermediate', 'Difficult', 'Advanced'] as const;
export type Level = (typeof LEVELS)[number];

export const LEVEL_RANK: Record<Level, number> = { Beginner: 0, Intermediate: 1, Difficult: 2, Advanced: 3 };

// Medium problems that need a less obvious idea (DP state, tricky backtracking, graph ordering,
// binary search on rotated or answer space) are pulled up from Intermediate to Difficult.
const DIFFICULT_MEDIUMS = new Set([
  'word-search',
  'combination-sum-ii',
  'subsets-ii',
  'task-scheduler',
  'time-based-key-value-store',
  'search-in-rotated-sorted-array',
  'find-minimum-in-rotated-sorted-array',
  'word-break',
  'longest-increasing-subsequence',
  'jump-game-ii',
  'gas-station',
  'non-overlapping-intervals',
  'house-robber-ii',
  'decode-ways',
  'maximum-product-subarray',
  'coin-change',
  'longest-palindromic-substring',
  'reorder-list',
  'lru-cache',
  'find-the-duplicate-number',
  'sum-of-two-integers',
  'longest-repeating-character-replacement',
  'car-fleet',
  'course-schedule-ii',
  'pacific-atlantic-water-flow',
  'surrounded-regions',
]);

export function levelOf(problem: Pick<CodingProblem, 'id' | 'difficulty'>): Level {
  if (problem.difficulty === 'Easy') return 'Beginner';
  if (problem.difficulty === 'Hard') return 'Advanced';
  return DIFFICULT_MEDIUMS.has(problem.id) ? 'Difficult' : 'Intermediate';
}
